-- AlterTable
ALTER TABLE "ComputeResource" ALTER COLUMN "hourlyRate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "totalCost" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "balance" SET DEFAULT 0,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;
