[tls]
# Disabled for local development
# cert_file = "certs/localhost.pem"
# key_file = "certs/localhost-key.pem"

[tls.dev]
enabled = false

# Рекомендуемые настройки
ciphers = [
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
]

min_protocol_version = "TLSv1.2"
