[tls]
cert_file = "/path/to/cert.pem"
key_file = "/path/to/key.pem"

# Рекомендуемые настройки
ciphers = [
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
]

min_protocol_version = "TLSv1.2"
