name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'rust-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'rust-backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rust-backend/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      working-directory: ./rust-backend
      run: cargo build --release
    
    - name: Run tests
      working-directory: ./rust-backend
      run: cargo test --release
