name: Backend Deploy

on:
  workflow_run:
    workflows: ["Backend CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Build release binary
      working-directory: ./rust-backend
      run: cargo build --release
    
    - name: Deploy to production
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "mkdir -p ~/aura/backend && \
           systemctl stop aura-backend"
        
        scp -o StrictHostKeyChecking=no \
          ./rust-backend/target/release/aura-core \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/aura/backend/
        
        scp -o StrictHostKeyChecking=no \
          ./rust-backend/prod.toml \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/aura/backend/
        
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "systemctl start aura-backend"
