name: Backend Release

on:
  push:
    tags:
      - 'backend-v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          cd rust-backend
          cargo test --release

  build:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build backend
        run: |
          cd rust-backend
          cargo build --release
      - name: Compress artifact
        run: |
          mkdir -p dist
          tar -czf dist/aura-backend-${{ matrix.os }}.tar.gz -C rust-backend/target/release aura-backend
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aura-backend-${{ matrix.os }}
          path: dist/aura-backend-${{ matrix.os }}.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: 'Multi-platform release of Aura backend.'
          files: |
            dist/aura-backend-ubuntu-latest.tar.gz
            dist/aura-backend-macos-latest.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
