name: Payment Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install -y libleptonica-dev tesseract-ocr
          export TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
          curl -s http://localhost:8080/api/payment/metrics | \
          jq -e '.pending_topups < 10' || \
          (echo "Too many pending topups!" && exit 1)
